name: Build & Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v1
        with:
          version: v0.60.0
          extended: true
      - name: Check Artifacts
        run: head public/portfolio/index.html
      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
      - name: Check Artifacts
        run: head portfolio/index.html
      - name: Upload FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: "contact.celinelenoble.com/files/website/"
          options: "-p --transfer-all --ignore-time --delete -v"

